apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      values: |
        replicas: 2
        minimumMasterNodes: 1
        resources: 
          requests: 
            cpu: "100"
            memory: "512 Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true 